openapi: 3.0.3
info:
  title: Tipo de Cambio DOF API
  version: 1.0.0
  description: API para obtener el tipo de cambio del DOF, validar con FIX de Banxico, registrar en Google Sheets y calcular promedios.
servers:
  - url: https://tc-dof.onrender.com   # ⬅️ tu URL de Render
    description: Producción

components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key
  schemas:
    HealthResponse:
      type: object
      required: [status, timestamp, service]
      properties:
        status: { type: string, enum: [ok] }
        timestamp: { type: string, format: date-time }
        service: { type: string }
    TipoCambioResponse:
      type: object
      required: [fecha, tc_dof, fuente, publicado_a_las, nota_validacion]
      properties:
        fecha: { type: string, format: date, example: '2025-09-26' }
        tc_dof: { type: number, format: double, example: 18.4457 }
        tc_fix: { type: number, format: double, nullable: true, example: 18.3825 }
        fuente: { type: string, example: DOF }
        publicado_a_las: { type: string, example: '12:00' }
        nota_validacion:
          type: string
          description: >
            Posibles valores: OK, DIF_DOF_BANX, SIN_PUBLICACION_FECHA; USADO_ANTERIOR=YYYY-MM-DD, AUSENTE_DOY.
          example: OK
    RegistrarRequest:
      type: object
      required: [tc_dof]
      properties:
        fecha: { type: string, format: date, example: '2025-09-26' }
        tc_dof: { type: number, format: double, example: 18.4457 }
        fuente: { type: string, example: DOF }
        publicado_a_las: { type: string, example: '12:00' }
        nota_validacion: { type: string, example: OK }
    RegistrarResponse:
      type: object
      required: [message, fecha, tc_dof]
      properties:
        message: { type: string, example: Registro insertado correctamente }
        fecha: { type: string, format: date, example: '2025-09-26' }
        tc_dof: { type: number, format: double, example: 18.4457 }
    PromediosResponse:
      type: object
      properties:
        promedio_semanal:
          type: object
          nullable: true
          properties:
            isoYear: { type: integer, example: 2025 }
            isoWeek: { type: integer, example: 40 }
            valor: { type: number, format: double, example: 18.1500 }
            diasConsiderados: { type: integer, example: 5 }
        promedio_mensual:
          type: object
          nullable: true
          properties:
            year: { type: integer, example: 2025 }
            month: { type: integer, example: 9 }
            valor: { type: number, format: double, example: 18.0900 }
            diasConsiderados: { type: integer, example: 22 }

security:
  - ApiKeyAuth: []   # ⬅️ así el GPT siempre envía X-API-Key

tags:
  - name: Health
  - name: Tipo de Cambio

paths:
  /health:
    get:
      tags: [Health]
      summary: Verifica el estado del servicio
      operationId: getHealth
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema: { $ref: '#/components/schemas/HealthResponse' }

  /tipo-cambio:
    get:
      tags: [Tipo de Cambio]
      summary: Obtiene el tipo de cambio del DOF (con fallback si aplica)
      operationId: getTipoCambio
      parameters:
        - in: query
          name: fecha
          required: true
          description: Fecha en formato YYYY-MM-DD
          schema: { type: string, format: date, example: '2025-09-26' }
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema: { $ref: '#/components/schemas/TipoCambioResponse' }
        '404':
          description: No hay publicación para la fecha (ni tras reintentos)

  /registrar:
    post:
      tags: [Tipo de Cambio]
      summary: Registra un tipo de cambio en Google Sheets
      operationId: registrarTipoCambio
      requestBody:
        required: true
        content:
          application/json:
            schema: { $ref: '#/components/schemas/RegistrarRequest' }
      responses:
        '200':     # ⬅️ usa 201 si tu endpoint realmente devuelve 201
          description: registrado
          content:
            application/json:
              schema: { $ref: '#/components/schemas/RegistrarResponse' }
        '409':
          description: La fecha ya está registrada

  /promedios:
    get:
      tags: [Tipo de Cambio]
      summary: Calcula promedios semanal (ISO) y mensual
      operationId: getPromedios
      parameters:
        - in: query
          name: from
          schema: { type: string, format: date }
        - in: query
          name: to
          schema: { type: string, format: date }
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema: { $ref: '#/components/schemas/PromediosResponse' }
